---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

env:
  global:
    - ROLE_NAME: ovhbastion

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install --upgrade pip
  - pip install ansible ansible-lint yamllint
  - ansible --version
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

before_script:
  - cd ../
  - mv ansible-$ROLE_NAME adamsbytes.$ROLE_NAME
  - cd adamsbytes.$ROLE_NAME

script:
  # Run tests
  - ansible-lint ./
  - yamllint ./

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/