---
language: python
dist: focal
python: "3.9"

branches:
  only:
    - main

env:
  global:
    - ROLE_NAME: ovhbastion
    - NEW_VERSION_TAG: v1.0.5
    - NEW_VERSION_DESCRIPTION="Improved metadata and project attributes."

addons:
  apt:
    packages:
      - python3-pip
      - shellcheck

install:
  - pip install --upgrade pip
  - pip install ansible ansible-lint yamllint
  - ansible --version

script:
  - ansible-lint ./
  - yamllint ./
  - shellcheck ./.travis/*.sh

after_success:
  - ./.travis/push-tags.sh

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    if: type = push
