---
language: python
dist: focal
python: "3.9"
sudo: false

branches:
  only:
    - main

env:
  global:
    - ROLE_NAME: ovhbastion
    - NEW_VERSION_TAG: v1.0.4
    - NEW_VERSION_DESCRIPTION: "Enhanced pipeline and updated README"

addons:
  apt:
    packages:
      - python3-pip

install:
  - pip install --upgrade pip
  - pip install ansible ansible-lint yamllint shellcheck
  - ansible --version

script:
  - ansible-lint ./
  - yamllint ./
  - shellcheck ./.travis/*.sh

after_success:
  - ./.travis/push-tags.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
    if: type = push
