---
# tasks file for ovhbastion
- name: create directory for bastion install
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  loop:
    - "{{ bastion_install_dir }}"

- name: extract bastion files to install directory
  unarchive:
    src: "{{ bastion_package_url }}"
    dest: "{{ bastion_install_dir }}"
    remote_src: yes
    extra_opts:
    - --strip-components=1

- name: install ttyrec deb package
  apt:
    deb: "{{ ttyrec_package_url }}"
    update_cache: yes

- name: install bastion packages
  shell:
    cmd: /opt/bastion/bin/admin/packages-check.sh -i -s -t >> ansible-install-log.txt
    chdir: "{{ bastion_install_dir }}"
